### ISSUE TITLE
Sidecar not injected

### ISSUE THREAD

**Issue by vbottu** [salesforce/generic-sidecar-injector#25]
Hi,
I have tried this side car injector using the helm chart provided and the installation was successful and I don't see any errors in the sidecarinjector pod. Below are the sidecarconfig and mutation config used
```
apiVersion:` v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-webhook-configmap
  namespace: {{ .Values.namespace }}
data:
  sidecarconfig.yaml: |
    containers: 
    - name: test
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
      - mountPath: /etc
        name: nginx-config-volume
    volumes:
    - configMap:
        defaultMode: 420
        name: nginx-config
      name: fluentd-config-volume
  mutationconfig.yaml: |
    mutationConfigs: 
    - name: "mutation-config-1"
    annotationNamespace: "nginx-sidecar"
    annotationTrigger: "inject"
    containers: ["test"]
```
I have used the annotation `nginx-sidecar/inject: enabled` on my pod and I don't see any sidecar injected into my deployment.

Kubernetes Version: 1.16.15

Admission controller is enabled.
